name: Feature Request
description: 新機能の提案と既存機能の改善案を入力してください。
type: task
labels: enhancement

body:
  - type: textarea
    id: task_overview
    attributes:
      label: 内容

  - type: textarea
    id: reason
    attributes:
      label: 背景と目的
